[tool.mypy]
exclude = '/_version\.py$'
follow_imports = "skip"

[[tool.mypy.overrides]]
module = "snps.*"
ignore_missing_imports = true

# https://github.com/astral-sh/ruff/issues/465#issuecomment-1783684428
[tool.ruff.lint]
extend-select = ["I"]
